/*
 * Copyright Mozilla Public License 1.1
 */

window.config = {
    baseUrl: 'js',
    urlArgs: "bust=" + 9,
    paths: {
        module : '../module',
        "jquery" : "jquery/jquery-1.8.2.min",
        "jquery-ui" : "jquery/jquery-ui.min",
        "jquery.url" : "jquery/jquery.url",
        "jquery.nano" : "jquery/jquery.nano",
        "jquery.freebase_suggest.min" : "jquery/jquery.freebase_suggest.min",
        "jquery.json.min" : "jquery/jquery.json.min",
        "jquery.tinysort.min" : "jquery/jquery.tinysort.min",
        "jquery.cookie" :  "jquery/jquery.cookie",
        "jquery.colorbox" : "jquery/jquery.colorbox-min",
        "org/cometd" : "cometd/cometd",
        "jquery.cometd" : "jquery/cometd/jquery.cometd",
        "jquery.cometd-ack" : "jquery/cometd/jquery.cometd-ack",
        "jquery.cometd-reload" : "jquery/cometd/jquery.cometd-reload",
        "jquery.cometd-timestamp" : "jquery/cometd/jquery.cometd-timestamp",
        "jquery.cometd-timesync" : "jquery/cometd/jquery.cometd-timesync",
        "org/cometd/AckExtension" : "cometd/plugins/AckExtension",
        "org/cometd/ReloadExtension" : "cometd/plugins/ReloadExtension",
        "org/cometd/TimeStampExtension" : "cometd/plugins/TimeStampExtension",
        "org/cometd/TimeSyncExtension" : "cometd/plugins/TimeSyncExtension",
        "triple_brain.overlay_dialog" : "triple_brain/triple_brain.overlay_dialog",
        "triple_brain.ui.utils" : "triple_brain/triple_brain.ui.utils",
        "triple_brain.user" : "triple_brain/mind_map/triple_brain.user",
        "triple_brain.login_handler" : "triple_brain/triple_brain.login_handler",
        "triple_brain.registration_handler" : "triple_brain/triple_brain.registration_handler",
        "triple_brain.event_bus" : "triple_brain/triple_brain.event_bus",
        "triple_brain.drag_scroll" : "triple_brain/triple_brain.drag_scroll",
        "triple_brain.ui.graph" : "triple_brain/mind_map/triple_brain.ui.graph",
        "triple_brain.ui.vertex" : "triple_brain/mind_map/vertex/triple_brain.ui.vertex",
        "triple_brain.ui.vertex_html_builder" : "triple_brain/mind_map/vertex/triple_brain.ui.vertex_html_builder",
        "triple_brain.ui.vertex_segments" : "triple_brain/mind_map/vertex/triple_brain.ui.vertex_segments",
        "triple_brain.search" : "triple_brain/mind_map/triple_brain.search",
        "triple_brain.ui.search" : "triple_brain/mind_map/triple_brain.ui.search",
        "triple_brain.ui.depth_slider" : "triple_brain/mind_map/triple_brain.ui.depth_slider",
        "triple_brain.mind-map_template" : "triple_brain/mind_map/triple_brain.mind-map_template",
        "triple_brain.config" : "triple_brain/triple_brain.config",
        "triple_brain.id_uri" : "triple_brain/triple_brain.id_uri",
        "triple_brain.ui.arrow_line" : "triple_brain/mind_map/edge/triple_brain.ui.arrow_line",
        "triple_brain.vertex" : "triple_brain/mind_map/triple_brain.vertex",
        "triple_brain.ui.edge" : "triple_brain/mind_map/edge/triple_brain.ui.edge",
        "triple_brain.edge" : "triple_brain/mind_map/triple_brain.edge",
        "triple_brain.suggestion" : "triple_brain/mind_map/triple_brain.suggestion",
        "triple_brain.external_resource" : "triple_brain/mind_map/triple_brain.external_resource",
        "triple_brain.peripheral_menu" : "triple_brain/mind_map/triple_brain.peripheral_menu",
        "triple_brain.ui.identification_menu" : "triple_brain/mind_map/vertex/triple_brain.ui.identification_menu",
        "triple_brain.ui.suggestion_menu" : "triple_brain/mind_map/vertex/triple_brain.ui.suggestion_menu",
        "triple_brain.ui.image_menu" : "triple_brain/mind_map/vertex/triple_brain.ui.image_menu",
        "triple_brain.ui.all" : "triple_brain/mind_map/triple_brain.ui.all",
        "triple_brain.point" : "triple_brain/mind_map/triple_brain.point",
        "triple_brain.segment" : "triple_brain/mind_map/triple_brain.segment",
        "triple_brain.ui.vertex_hidden_neighbor_properties_indicator" : "triple_brain/mind_map/vertex/hidden_neighbor_properties/triple_brain.ui.vertex_hidden_neighbor_properties_indicator",
        "triple_brain.ui.vertex_and_edge_common" : "triple_brain/mind_map/triple_brain.ui.vertex_and_edge_common",
        "triple_brain.freebase" : "triple_brain/mind_map/triple_brain.freebase",
        "triple_brain.transform_matrix_2d" : "triple_brain/mind_map/triple_brain.transform_matrix_2d",
        "triple_brain.error" : "triple_brain/triple_brain.error",
        "triple_brain.ui.triple" : "triple_brain/mind_map/triple_brain.ui.triple",
        "triple_brain.template" : "triple_brain/triple_brain.template",
        "triple_brain.ui.vertex_hidden_neighbor_properties_indicator_dashed_segment" : "triple_brain/mind_map/vertex/hidden_neighbor_properties/triple_brain.ui.vertex_hidden_neighbor_properties_indicator_dashed_segment",
        "triple_brain.ui.left_panel" : "triple_brain/mind_map/triple_brain.ui.left_panel",
        "triple_brain.image" : "triple_brain/triple_brain.image",
        "triple_brain.server_subscriber" : "triple_brain/triple_brain.server_subscriber",
        "triple_brain.graph" : "triple_brain/mind_map/triple_brain.graph",
        "triple_brain.graph_displayer" : "triple_brain/mind_map/vertices_and_edges/triple_brain.graph_displayer",
        "triple_brain.graph_displayer_as_graph" : "triple_brain/mind_map/vertices_and_edges/graph/triple_brain.graph_displayer_as_graph",
        "triple_brain.graph_displayer_as_graph_edge_creator" : "triple_brain/mind_map/vertices_and_edges/graph/triple_brain.graph_displayer_as_graph_edge_creator",
        "triple_brain.graph_displayer_as_absolute_tree" : "triple_brain/mind_map/vertices_and_edges/tree/absolute/triple_brain.graph_displayer_as_absolute_tree",
        "triple_brain.graph_displayer_as_relative_tree" : "triple_brain/mind_map/vertices_and_edges/tree/relative/triple_brain.graph_displayer_as_relative_tree",
        "triple_brain.relative_tree_displayer_templates" : "triple_brain/mind_map/vertices_and_edges/tree/relative/triple_brain.relative_tree_displayer_templates",
        "triple_brain.graph_displayer_as_tree_common" : "triple_brain/mind_map/vertices_and_edges/tree/triple_brain.graph_displayer_as_tree_common",
        "triple_brain.mind_map_info" : "triple_brain/mind_map/triple_brain.mind_map_info"
    },
    shim : {
        "jquery-ui" : ["jquery"],
        "jquery.url" : ["jquery"],
        "jquery.nano" : ["jquery"],
        "jquery.freebase_suggest.min" : ["jquery"],
        "jquery.json.min" : ["jquery"],
        "jquery.tinysort.min" : ["jquery"],
        "jquery.cookie" :  ["jquery"],
        "jquery.cometd" : ["jquery"],
        "jquery.cometd-ack" : ["jquery"],
        "jquery.cometd-reload" : ["jquery"],
        "jquery.cometd-timestamp" : ["jquery"],
        "jquery.cometd-timesync" : ["jquery"],
        "jquery.colorbox" : ["jquery"]
    }
};